from __future__ import annotations

from importlib.metadata import version as _version

from . import log as _log  # noqa: F401 -- attaches the package logger's NullHandler
from .exceptions import (
    DHCPError as DHCPError,
    DHCPDecodeError as DHCPDecodeError,
    DHCPValueError as DHCPValueError,
    NoClientIdentityError as NoClientIdentityError,
)
from .listener import (
    DHCPListener as DHCPListener,
    AsyncDHCPListener as AsyncDHCPListener,
    DHCPTransport as DHCPTransport,
    UDPTransport as UDPTransport,
    PktInfoUDPTransport as PktInfoUDPTransport,
    DHCPRequestContext as DHCPRequestContext,
)
from .packet.message import DHCPMessage as DHCPMessage
from .options import (
    DHCPOptions as DHCPOptions,
    DHCPOption as DHCPOption,
    DHCPOptionCode as DHCPOptionCode,
)
from .options.type import (
    DHCPOptionType as DHCPOptionType,
    DHCPOptionCodes as DHCPOptionCodes,
    ClasslessRoute as ClasslessRoute,
    PolicyFilter as PolicyFilter,
    StaticRoute as StaticRoute,
    DomainList as DomainList,
    UncompressedDomainList as UncompressedDomainList,
    ClientIdentifier as ClientIdentifier,
    OptionOverload as OptionOverload,
    UserClass as UserClass,
    TLVOption as TLVOption,
    VendorSpecificInformation as VendorSpecificInformation,
    RelayAgentInformation as RelayAgentInformation,
    VIVendorSpecificInformationRecord as VIVendorSpecificInformationRecord,
    VIVendorSpecificInformation as VIVendorSpecificInformation,
    VIVendorClassRecord as VIVendorClassRecord,
    VIVendorClass as VIVendorClass,
    RDNSSSelection as RDNSSSelection,
    URIList as URIList,
    CccOption as CccOption,
    CccSubOption as CccSubOption,
    CccPrimaryDhcpServerAddress as CccPrimaryDhcpServerAddress,
    CccSecondaryDhcpServerAddress as CccSecondaryDhcpServerAddress,
    CccProvisioningServerAddress as CccProvisioningServerAddress,
    CccProvisioningServerFqdn as CccProvisioningServerFqdn,
    CccKerberosRealmName as CccKerberosRealmName,
    CccAsReqAsRepBackoffRetry as CccAsReqAsRepBackoffRetry,
    CccApReqApRepBackoffRetry as CccApReqApRepBackoffRetry,
    CccTicketGrantingServerUtilization as CccTicketGrantingServerUtilization,
    CccProvisioningTimer as CccProvisioningTimer,
    CccSecurityTicketControl as CccSecurityTicketControl,
    CccKdcServerAddressList as CccKdcServerAddressList,
    CccPrimaryDhcpServerAddressSubOption as CccPrimaryDhcpServerAddressSubOption,
    CccSecondaryDhcpServerAddressSubOption as CccSecondaryDhcpServerAddressSubOption,
    CccProvisioningServerAddressSubOption as CccProvisioningServerAddressSubOption,
    CccAsReqAsRepBackoffRetrySubOption as CccAsReqAsRepBackoffRetrySubOption,
    CccApReqApRepBackoffRetrySubOption as CccApReqApRepBackoffRetrySubOption,
    CccKerberosRealmNameSubOption as CccKerberosRealmNameSubOption,
    CccTicketGrantingServerUtilizationSubOption as CccTicketGrantingServerUtilizationSubOption,
    CccProvisioningTimerSubOption as CccProvisioningTimerSubOption,
    CccSecurityTicketControlSubOption as CccSecurityTicketControlSubOption,
    CccKdcServerAddressSubOption as CccKdcServerAddressSubOption,
    MoSIPv4AddressRecord as MoSIPv4AddressRecord,
    MoSFQDNRecord as MoSFQDNRecord,
    MoSIPv4AddressList as MoSIPv4AddressList,
    MoSFQDNList as MoSFQDNList,
    U8 as U8,
    U16 as U16,
    U32 as U32,
)
from .network import (
    IPv4 as IPv4,
    IPv4Interface as IPv4Interface,
    IPv4Network as IPv4Network,
    MACAddress as MACAddress,
    SocketAddress as SocketAddress,
    NetworkInterface as NetworkInterface,
)
from .server import DHCPServer as DHCPServer, AsyncDHCPServer as AsyncDHCPServer
from .client import DHCPClient as DHCPClient
from .relay import DHCPRelay as DHCPRelay, AsyncDHCPRelay as AsyncDHCPRelay
from .capture import (
    CaptureEvent as CaptureEvent,
    DHCPCapture as DHCPCapture,
    AsyncDHCPCapture as AsyncDHCPCapture,
    compile_capture_filter as compile_capture_filter,
)
from .lease import (
    DHCPLease as DHCPLease,
    LeaseBackend as LeaseBackend,
    InMemoryLeaseBackend as InMemoryLeaseBackend,
    FileLeaseBackend as FileLeaseBackend,
)

__version__ = _version("pydhcp")

__all__ = [
    "__version__",
    "DHCPError",
    "DHCPDecodeError",
    "DHCPValueError",
    "NoClientIdentityError",
    "DHCPListener",
    "AsyncDHCPListener",
    "DHCPTransport",
    "UDPTransport",
    "PktInfoUDPTransport",
    "DHCPRequestContext",
    "DHCPMessage",
    "DHCPOptions",
    "DHCPOption",
    "DHCPOptionCode",
    "DHCPOptionType",
    "DHCPOptionCodes",
    "ClasslessRoute",
    "PolicyFilter",
    "StaticRoute",
    "DomainList",
    "UncompressedDomainList",
    "ClientIdentifier",
    "OptionOverload",
    "UserClass",
    "TLVOption",
    "VendorSpecificInformation",
    "RelayAgentInformation",
    "VIVendorSpecificInformationRecord",
    "VIVendorSpecificInformation",
    "VIVendorClassRecord",
    "VIVendorClass",
    "RDNSSSelection",
    "URIList",
    "CccOption",
    "CccSubOption",
    "CccPrimaryDhcpServerAddress",
    "CccSecondaryDhcpServerAddress",
    "CccProvisioningServerAddress",
    "CccProvisioningServerFqdn",
    "CccKerberosRealmName",
    "CccAsReqAsRepBackoffRetry",
    "CccApReqApRepBackoffRetry",
    "CccTicketGrantingServerUtilization",
    "CccProvisioningTimer",
    "CccSecurityTicketControl",
    "CccKdcServerAddressList",
    "CccPrimaryDhcpServerAddressSubOption",
    "CccSecondaryDhcpServerAddressSubOption",
    "CccProvisioningServerAddressSubOption",
    "CccAsReqAsRepBackoffRetrySubOption",
    "CccApReqApRepBackoffRetrySubOption",
    "CccKerberosRealmNameSubOption",
    "CccTicketGrantingServerUtilizationSubOption",
    "CccProvisioningTimerSubOption",
    "CccSecurityTicketControlSubOption",
    "CccKdcServerAddressSubOption",
    "MoSIPv4AddressRecord",
    "MoSFQDNRecord",
    "MoSIPv4AddressList",
    "MoSFQDNList",
    "U8",
    "U16",
    "U32",
    "IPv4",
    "IPv4Interface",
    "IPv4Network",
    "MACAddress",
    "SocketAddress",
    "NetworkInterface",
    "DHCPServer",
    "AsyncDHCPServer",
    "DHCPClient",
    "DHCPRelay",
    "AsyncDHCPRelay",
    "CaptureEvent",
    "DHCPCapture",
    "AsyncDHCPCapture",
    "compile_capture_filter",
    "DHCPLease",
    "LeaseBackend",
    "InMemoryLeaseBackend",
    "FileLeaseBackend",
]
