"""`docs/options.md` lists every option code the registry names, and says so truthfully.

The table between the page's markers is generated by `docs/options_table.py`; this test
reads the page as a user would and compares each row with the registry, so a code added,
removed or given another codec fails here until the page is regenerated.
"""

import importlib.util
import re
from pathlib import Path

import pytest

from pydhcp.options import DHCPOptionCode

_DOCS = Path(__file__).resolve().parent.parent / "docs"
_PAGE = _DOCS / "options.md"
_ROW = re.compile(r"^\| (\d+) \| `(\w+)` \| (.+?) \| (.+?) \| (.*?) \|$")


def _generator():
    spec = importlib.util.spec_from_file_location(
        "options_table", _DOCS / "options_table.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _page_rows(text):
    start = text.index("<!-- options-table:begin -->")
    stop = text.index("<!-- options-table:end -->")
    rows = {}
    for line in text[start:stop].splitlines():
        found = _ROW.match(line)
        if found:
            rows[int(found.group(1))] = (found.group(2), found.group(3))
    return rows


def _registry():
    names = {}
    for name, member in DHCPOptionCode.__members__.items():
        names.setdefault(int(member), name)
    return names


def test_the_page_lists_every_code_the_registry_names():
    page = _page_rows(_PAGE.read_text(encoding="utf-8"))
    registry = _registry()
    assert set(page) == set(registry)
    assert {code: name for code, (name, _codec) in page.items()} == registry
    assert len([code for code in page if code not in (0, 255)]) == 161


def test_each_row_names_the_codec_the_registry_binds():
    page = _page_rows(_PAGE.read_text(encoding="utf-8"))
    for code, (_name, codec) in page.items():
        if code in (0, 255):
            assert codec == "framing"
            continue
        kind = DHCPOptionCode(code).get_type().__name__
        expected = f"`{kind}` (opaque)" if kind == "Bytes" else f"`{kind}`"
        assert codec == expected, code


def test_the_page_is_what_the_generator_writes():
    text = _PAGE.read_text(encoding="utf-8")
    generator = _generator()
    assert generator.current_block(text) == generator.block(text)
    assert generator.main(["--check"]) == 0


def test_a_row_that_disagrees_with_the_registry_is_found():
    text = _PAGE.read_text(encoding="utf-8")
    changed = text.replace(
        "| 1 | `SUBNET_MASK` | `IPv4AddressOption` |", "| 1 | `SUBNET_MASK` | `U32` |"
    )
    assert changed != text
    assert _page_rows(changed)[1] != _page_rows(text)[1]
    generator = _generator()
    assert generator.current_block(changed) != generator.block(changed)
    dropped = "\n".join(
        line for line in text.splitlines() if not line.startswith("| 252 |")
    )
    assert 252 not in _page_rows(dropped)


@pytest.mark.parametrize("code", [0, 255])
def test_the_markers_of_the_stream_are_framing_not_options(code):
    assert _page_rows(_PAGE.read_text(encoding="utf-8"))[code][1] == "framing"
