"""`docs/conformance.md` agrees with the conformance data, and places every case once.

The tables of the page are generated by `docs/conformance_table.py` from
`tests/conformance/features.json` and `deviations.json`; this test runs its check and
reads the page the way a user does.
"""

import importlib.util
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "tests" / "conformance"
PAGE = ROOT / "docs" / "conformance.md"
FEATURES = json.loads((DATA / "features.json").read_text(encoding="utf-8"))
CASES = sorted(p.name for p in (DATA / "cases").iterdir() if p.is_dir())


def _generator():
    spec = importlib.util.spec_from_file_location(
        "conformance_table", ROOT / "docs" / "conformance_table.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_page_is_what_the_generator_writes():
    assert _generator().main(["--check"]) == 0


def test_every_case_is_in_exactly_one_row():
    placed = [name for row in FEATURES for name in row["cases"]]

    assert sorted(placed) == CASES


def test_a_row_says_what_it_is():
    for row in FEATURES:
        assert set(row) == {"role", "feature", "rfc", "implemented", "cases", "note"}
        assert row["role"] in ("server", "client", "relay")
        assert row["feature"] and isinstance(row["implemented"], bool)
        for name in row["cases"]:
            assert name.split("-", 1)[0] == row["role"], name


def test_the_page_holds_one_table_row_per_feature_and_per_deviation():
    text = PAGE.read_text(encoding="utf-8")
    coverage = text.split("<!-- coverage-table:begin -->")[1].split(
        "<!-- coverage-table:end -->"
    )[0]
    differences = text.split("<!-- differences-table:begin -->")[1].split(
        "<!-- differences-table:end -->"
    )[0]
    deviations = json.loads((DATA / "deviations.json").read_text(encoding="utf-8"))

    assert len(re.findall(r"^\| (?:server|client|relay) \|", coverage, re.M)) == len(
        FEATURES
    )
    assert re.findall(r"^\| `([a-z0-9-]+)` \|", differences, re.M) == [
        d["id"] for d in deviations
    ]


def test_a_stale_page_is_found():
    generator = _generator()
    text = PAGE.read_text(encoding="utf-8")
    stale = text.replace("| server | DHCPRELEASE |", "| server | DHCPRELEASED |")

    assert stale != text
    assert generator.fresh(stale) != stale
