from __future__ import annotations

from ._base import (
    DHCPOptionType as DHCPOptionType,
    OptionCodec as OptionCodec,
    List as List,
    RecordList as RecordList,
    DHCPOptionCodes as DHCPOptionCodes,
)

# The submodule order below is alphabetical and carries no meaning. It used to
# carry one: `ccc` lived outside this package and imported `.type` back, so it
# worked only while it was imported last, and hoisting this block produced an
# ImportError from a partially initialised module. It is now a sibling that
# imports `.base`/`.addresses`/`.scalar` directly, so any order works.
from ._ccc import (
    CCCOption as CCCOption,
    CCCSubOption as CCCSubOption,
    CCCPrimaryDHCPServerAddress as CCCPrimaryDHCPServerAddress,
    CCCSecondaryDHCPServerAddress as CCCSecondaryDHCPServerAddress,
    CCCProvisioningServerAddress as CCCProvisioningServerAddress,
    CCCProvisioningServerFQDN as CCCProvisioningServerFQDN,
    CCCKerberosRealmName as CCCKerberosRealmName,
    CCCASBackoffRetry as CCCASBackoffRetry,
    CCCAPBackoffRetry as CCCAPBackoffRetry,
    CCCTicketGrantingServerUtilization as CCCTicketGrantingServerUtilization,
    CCCProvisioningTimer as CCCProvisioningTimer,
    CCCSecurityTicketControl as CCCSecurityTicketControl,
    CCCKDCServerAddressList as CCCKDCServerAddressList,
    CCCPrimaryDHCPServerAddressSubOption as CCCPrimaryDHCPServerAddressSubOption,
    CCCSecondaryDHCPServerAddressSubOption as CCCSecondaryDHCPServerAddressSubOption,
    CCCProvisioningServerAddressSubOption as CCCProvisioningServerAddressSubOption,
    CCCASBackoffRetrySubOption as CCCASBackoffRetrySubOption,
    CCCAPBackoffRetrySubOption as CCCAPBackoffRetrySubOption,
    CCCKerberosRealmNameSubOption as CCCKerberosRealmNameSubOption,
    CCCTicketGrantingServerUtilizationSubOption as CCCTicketGrantingServerUtilizationSubOption,
    CCCProvisioningTimerSubOption as CCCProvisioningTimerSubOption,
    CCCSecurityTicketControlSubOption as CCCSecurityTicketControlSubOption,
    CCCKDCServerAddressSubOption as CCCKDCServerAddressSubOption,
)
from ._mos import (
    MoSIPv4AddressRecord as MoSIPv4AddressRecord,
    MoSFQDNRecord as MoSFQDNRecord,
    MoSIPv4AddressList as MoSIPv4AddressList,
    MoSFQDNList as MoSFQDNList,
)
from ._addresses import (
    IPv4AddressOption as IPv4AddressOption,
    ClasslessRoute as ClasslessRoute,
    PolicyFilter as PolicyFilter,
    StaticRoute as StaticRoute,
)
from ._domains import (
    DomainList as DomainList,
    UncompressedDomainList as UncompressedDomainList,
    DomainName as DomainName,
)
from ._fqdn import ClientFQDN as ClientFQDN
from ._servers import (
    RDNSSSelection as RDNSSSelection,
    SIPServers as SIPServers,
    StatusCode as StatusCode,
    PCPServerList as PCPServerList,
)
from ._scalar import (
    Bytes as Bytes,
    URIList as URIList,
    String as String,
    OctetString as OctetString,
    Boolean as Boolean,
    Flag as Flag,
    BaseFixedLengthInteger as BaseFixedLengthInteger,
    FixedLengthInteger as FixedLengthInteger,
    U8 as U8,
    U16 as U16,
    U32 as U32,
    I32 as I32,
    ClientIdentifier as ClientIdentifier,
    OptionOverload as OptionOverload,
)
from ._vendor import (
    UserClass as UserClass,
    TLVOption as TLVOption,
    EncapsulatedOptions as EncapsulatedOptions,
    VendorSpecificInformation as VendorSpecificInformation,
    RelayAgentInformation as RelayAgentInformation,
    VIVendorSpecificInformationRecord as VIVendorSpecificInformationRecord,
    VIVendorSpecificInformation as VIVendorSpecificInformation,
    VIVendorClassRecord as VIVendorClassRecord,
    VIVendorClass as VIVendorClass,
)

__all__ = [
    "DHCPOptionType",
    "OptionCodec",
    "List",
    "RecordList",
    "DHCPOptionCodes",
    "IPv4AddressOption",
    "ClasslessRoute",
    "PolicyFilter",
    "StaticRoute",
    "DomainList",
    "UncompressedDomainList",
    "RDNSSSelection",
    "ClientFQDN",
    "SIPServers",
    "DomainName",
    "StatusCode",
    "PCPServerList",
    "Bytes",
    "URIList",
    "String",
    "OctetString",
    "Boolean",
    "Flag",
    "BaseFixedLengthInteger",
    "FixedLengthInteger",
    "U8",
    "U16",
    "U32",
    "I32",
    "ClientIdentifier",
    "OptionOverload",
    "UserClass",
    "TLVOption",
    "EncapsulatedOptions",
    "VendorSpecificInformation",
    "RelayAgentInformation",
    "VIVendorSpecificInformationRecord",
    "VIVendorSpecificInformation",
    "VIVendorClassRecord",
    "VIVendorClass",
    "MoSIPv4AddressRecord",
    "MoSFQDNRecord",
    "MoSIPv4AddressList",
    "MoSFQDNList",
    "CCCOption",
    "CCCSubOption",
    "CCCPrimaryDHCPServerAddress",
    "CCCSecondaryDHCPServerAddress",
    "CCCProvisioningServerAddress",
    "CCCProvisioningServerFQDN",
    "CCCKerberosRealmName",
    "CCCASBackoffRetry",
    "CCCAPBackoffRetry",
    "CCCTicketGrantingServerUtilization",
    "CCCProvisioningTimer",
    "CCCSecurityTicketControl",
    "CCCKDCServerAddressList",
    "CCCPrimaryDHCPServerAddressSubOption",
    "CCCSecondaryDHCPServerAddressSubOption",
    "CCCProvisioningServerAddressSubOption",
    "CCCASBackoffRetrySubOption",
    "CCCAPBackoffRetrySubOption",
    "CCCKerberosRealmNameSubOption",
    "CCCTicketGrantingServerUtilizationSubOption",
    "CCCProvisioningTimerSubOption",
    "CCCSecurityTicketControlSubOption",
    "CCCKDCServerAddressSubOption",
]
